# Job name has to be `pages`. See https://docs.gitlab.com/ee/user/project/pages/#how-it-works

pages:
  image: node:lts-alpine
  before_script:
    - corepack enable
    - yarn install --immutable
  script:
    - yarn generate
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn/
  artifacts:
    paths:
      - .output/public
    expire_in: 1 hour
  publish: .output/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
